- amulet/deployer.py
- tests/test_deployer.py
Hello,
This patch takes care of transforming the `units` argument passed in `add_units()` to string to let subprocess run `juju add-unit foo -n N` otherwise a TypeError is raised.
Fixes https://bugs.launchpad.net/amulet/+bug/1413385
Best,
> When adding units to already deployed env transform to string

- .gitignore
- amulet/__init__.py
- amulet/charm.py
- amulet/deployer.py
- amulet/helpers.py
- setup.py
- tests/test_charm.py
- tests/test_deployer.py
- tests/test_gitcharm.py
Includes:
- new gitcharm charm class
- pass along to: & branch: key as part of service block
- boilerplate reduction for test writing for bundles
* `fail_if_timeout` contextmanager
* `from_bundle` factory
- sprinkling of path.py love
- refactor `amulet.deployer.Deployment.setup`
Make use of context managers and path.py to simplify flow.  Uses
tempdir to control flow wrt leaving debugging if there are errors.
Preserves semantics of cleanup arg.  Adds logging statements.
> Add handling charms in github + some refactoring

- tests/functional/test_sentry.py
I'm still seeing the problem when I run bundletester on my ubuntu-repository-cache charm.
The problem here is not that the timeout needs to be longer. The behavior suggests that Talisman.__init__() returns from wait_for_status() and progresses to UnitSentry.fromunitdata() which calls UnitSentry.upload_scripts() and attempts an scp prior to the unit actually being ready, because we're seeing the scp failure when this error presents itself. Once we get this working I see a problem having a timeout of 5 minutes in the add_unit that is not configurable as the ubuntu-repository-cache charm can take a while to spool up a unit.
If you look at tests/function/test_sentry.py (or any other testing for amulet) there is no test for add_unit after Deployer.setup is called to deploy the first N units. …
> test: Add test for add_unit

- amulet/sentry.py
- tests/functional/test_sentry.py
This PR addresses lp:1430488. 
The `waiter.wait` blocks for the full duration of the timeout, and `helpers.timeout` creates a signal-based timeout that's triggered when the timeout expires. This lead to `juju_agent()` being run against a unit still installing, which would throw an exception.
I made `waiter.wait` block for a smaller, arbitrary value of time (15 seconds), check the unit status, and repeat until it's ready or the timeout is expired.
> Fix wait() logic wrt timeout

- amulet/deployer.py
- tests/test_deployer.py
The target is passed on as --to to the juju add-unit command.
> Allow a target to be specified to Deployment.add_unit().

- amulet/deployer.py
- tests/test_deployer.py
Added action support to amulet.
> Added action support to amulet.

- amulet/deployer.py
We assume that constraints explicitly specified by the test are important and
take precedence (perhaps they specify some minimum requirements required to
successfully deploy, or are otherwise important for the semantics of the test
itself).
> Add unique constraints from the environment to those explicit in the test

- amulet/deployer.py
This inadvertently added a second handler (and therefore, duplicate logging output) to tests that were configuring their own logging.
> Don't configure logging in the library code

- amulet/sentry.py
- tests/functional/test_sentry.py
With the change to use 'juju ssh' in lieu of 'juju run' for the sentry
helpers, the default working directory is no longer the charm dir.  Work
around this by explicitly changing the directory (though not for
juju_agent, since the explicit charm dir interferes with it watching for
hooks).
> Fix sentry tools no longer defaulting to charm dir

- amulet/sentry.py
- tests/functional/test_sentry.py
The switch from 'juju ssh' to 'juju run' to prevent blocking caused the
helpers to fail against root-owned protected files / dirs.
> Fix amulet file helpers not using root

- Makefile
- amulet/deployer.py
- amulet/helpers.py
- amulet/sentry.py
- amulet/waiter.py
- tests/functional/test_sentry.py
- tests/test_deployer.py
- tests/test_helpers.py
- tests/test_sentry.py
- tests/test_waiter.py
Leveraging the new workload-status and agent-status, we can now tell with more certainty whether the system has settled down.  On top of this, wait_for_messages allows charm-specific matching on extended status messages.
Also refactored timeout logic in some portions to make testing faster and easier to debug.
Also fixed lint errors.
> Refactored wait logic to work better on Juju>=1.24

- amulet/sentry.py
To handle service not yet showing up in status (e.g., subordinates) and better match documented behavior.
> Minor fixes to wait_for_status

- amulet/deployer.py
Fixes this error: http://reports.vapour.ws/all-bundle-and-charm-results/charm-bundle-test-parent-1003/charm/azure/3
> Move tmp dir creation so setup() can be run more than once

- amulet/sentry.py
- tests/test_sentry.py
To preserve existing behavior, subordinates that have no relations (and thus can never possibly have a public-address or idle agent) should not block wait_for_status.  However, we do still want to block if a subordinate has been added & related, but has not yet attached to the appropriate units (usually due to a long-running hook blocking the subordinate install hook).
> Allow subordinates with no relations to pass wait_for_status

- amulet/sentry.py
- tests/test_sentry.py
Looking up a sentry for a unit that doesn't exist gives a horribly confusing error message, rather than a KeyError like it should.
Previously such a trivial fix nobody bothered to do so, it is more important now that this failure is being triggered a lot more in tests due to Juju 1.25 unit naming changes.
> Make sentry lookup failures explicit

- amulet/sentry.py
- tests/test_sentry.py
Per comments on last landing, return the sentry list in a stable order.
> Return sentry list in a stable order

- amulet/deployer.py
- amulet/sentry.py
AMULET_SETUP_TIMEOUT - If set, overrides the value passed to Deployment.setup()
AMULET_WAIT_TIMEOUT - If set, overrides the value passed to Deployment().sentry.wait()
Fixes #119.
> Pass timeouts via env vars.

- amulet/sentry.py
I haven't been able to repro #122, so I'm adding a way to debug when it happens again. Now we can print sentry.status and find out why we don't have the sentries we were expecting, e.g.:
```python
try:
lxd1_sentry = self.d.sentry['lxd'][1]
except KeyError, IndexError:
print(sentry.status)  # or something
```
Would be nice to get a patch release of this in ppa:juju/stable if possible so it can be used in OSCI.
> Save juju status on Talisman

- amulet/deployer.py
- amulet/sentry.py
- tests/functional/test_sentry.py
- tests/test_deployer.py
- tests/test_sentry.py
- Use set-config instead of set if juju2
- Update action commands for juju2
- s/agent-state/juju-status/ when inspecting juju2 status
- Free memory in tight status-checking loops. w/o this these
status loops leak gigs (literally) of memory if they run
long enough.
All tests (including functional) passed on juju1 and juju2.
> Fixes for juju2 compatibility

- amulet/deployer.py
The bundle keys have changed again, requiring the necessity to check for
an 'applications' key instead of only 'services' for the v4(?) format.
> Add check for 'application' in deployer wrapper

- amulet/charm.py
- amulet/deployer.py
Removing the deprecated method of importing from path.py.  The class name is "Path" and we can import that as "path" so there are no further code changes and now no deprecation warnings.
Fixes #158
> Importing path differently to avoid deprecation warnings.

- amulet/deployer.py
- amulet/sentry.py
> Fix upload_scripts and INFRA failures

- amulet/helpers.py
Not honoring JUJU_MODEL env variable is one of the causes of juju-solutions/bundletester#93 issue. If JUJU_MODEL env is set, Amulet needs to use the controller and model specified by the env variable rather than the output from the`juju switch` command. When working with multiple controllers, `juju switch` might have undesired result.
> Honor JUJU_MODEL environment variable.

- amulet/helpers.py
- amulet/sentry.py
- amulet/waiter.py
- tests/functional/test_sentry.py
- tests/test_helpers.py
In an attempt to fix #170, this improves the robustness of the scp process by explicitly specifying the model on the command line (to avoid having the active model switched out from under it) and retrying the ssh / scp commands a couple of times (to address transient network issues).
> (Hopefully) fix scp timeout by being explicit about model and retrying

- .travis.yml
- amulet/helpers.py
- tests/test_helpers.py
- tests/test_waiter.py
Use env vars to be explicit about the model.  (Fixes #178)
The placement of the CLI arg for specifying the model is complicated by the fact that Juju 1 has compound commands (such as `juju action do`) while other commands have to have the arg as early as possible (e.g., `juju scp` passes later args through to scp).  The env vars will override the active environment from the state file.
This also adds functional testing to the Travis config for Juju 2.  I'm not sure of a clean way to force it to use `juju-1` even if we install that, but I'm open to ideas.
> Fix model flag placement for Juju 1 compound commands

- .travis.yml
- .travis/bootstrap.sh
- .travis/cleanup.sh
- .travis/install.sh
- Use Juju stable ppa when testing 1.25 to ensure current version is exercised.
- Show nose test names and verdict.  Provides relevance to stderr output that might also exist (such as the wait test timeout messages).
- Show bash commands as executed in test runner.
- Require referenced env vars in test runner to exist.
> Increase travis test verbosity and use the stable PPA when testing Juju 1.25

- .travis.yml
- .travis/bootstrap.sh
- .travis/cleanup.sh
- .travis/install.sh
This tests Juju 1.x when testing Python 2.7 and 2.x when testing Python 3.5.  It would be more complete to test both versions of Juju with each version of Python, but that would make the tests take twice as long and I don't think there's really any cross-dependency between the Python version and Juju version.
> Test with Juju 1.x as well as 2.x
